# Site settings
baseurl = "https://alexmarc.us/"
languageCode = "en-us"
title = "Alex Marcus"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Alex Marcus"
    description = "The home and portfolio of Alex Marcus, a world explorer, professional software developer, and all-around solid teammate."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "mr@alexmarc.us"

    # Custom assets
	custom_css = ["css/am.css"]
	custom_js  = []

    [params.navigation]
        brand = "Alex Marc.us"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "am.png"
        name = "Alex Marcus"
        subtitle = "Problem Solver - Explorer - Team Builder"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            startDate = "Start Date"
            endDate = "End Date"
            category = "Category"
            buttontext = "Close"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "Alex Marcus is a Software Development Team Lead at [Level 11](//level11.com), working to join the worlds of programming and design into robust, intuitive, and cutting-edge user interfaces."
        right = "Since earning his degree in computer science and art, he has honed both skills in a number of web and software development roles across the United States.  With that knowledge he has started and led a number of successful development teams."
        # The center text will display below the left and right, centered on the page
        center = "Alex lives in Bremerton, WA with his partner [Chelsea](//chelseakellogg.com) and dog Bartleby.  Together they explore the wilds of the Pacific Northwest and beyond."

    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "&copy; 2018 Alex Marcus"

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Bremerton, WA", "Seattle, WA"]

        [params.footer.social]
            title = "Let's Connect!"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/in/amarcus"

            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/optimarcusprime"

            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "//twitter.com/optimarcusprime"
            
            [[params.footer.social.networks]]
                icon = "fa-instagram"
                link=  "//instagram.com/optimarcusprime"

        [params.footer.credits]
            title = "Powered By"
            text = "[Hugo](//gohugo.io) static site generator and a customized [Freelance](//github.com/digitalcraftsman/hugo-freelancer-theme) theme."
